# Multiple Linear Regression with sklearn - Exercise Solution

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. 

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data=pd.read_csv('real_estate_price_size_year.csv')

In [4]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Create the regression

### Declare the dependent and the independent variables

In [7]:
x=data[['size','year']]
y=data['price']

### Regression

In [8]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

### Find the intercept

In [9]:
reg.intercept_

-5772267.01746328

### Find the coefficients

In [10]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [13]:
r2=reg.score(x,y)
r2

0.7764803683276792

### Calculate the Adjusted R-squared

In [16]:
n=x.shape[0]
p=x.shape[1]
adjR=1-(1-r2)*(n-1)/(n-p-1)

In [17]:
adjR

0.7718717161282499

### Compare the R-squared and the Adjusted R-squared

adjusted R-squared is less than R-squared

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [22]:
X=[700,2009]
reg.predict(X)

ValueError: Expected 2D array, got 1D array instead:
array=[ 700 2009].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### Calculate the univariate p-values of the variables

In [27]:
from sklearn.feature_selection import f_regression

In [28]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [33]:
p_values=f_regression(x,y)[1]

In [34]:
p_values

array([8.12763222e-31, 3.57340758e-01])

### Create a summary table with your findings

In [43]:
reg_summary=pd.DataFrame(x.columns.values, columns=['Features'])
reg_summary['coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)
reg_summary

Features  coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357

Answer...